package Hyperclient::Constants;


use warnings;
use base 'Exporter';
use Config;

our @EXPORT_OK = ();
our %EXPORT_TAGS = (
		'returncode' => [
		'HYPERCLIENT_SUCCESS',
		'HYPERCLIENT_NOTFOUND',
		'HYPERCLIENT_SEARCHDONE',
		'HYPERCLIENT_CMPFAIL',
		'HYPERCLIENT_READONLY',
		'HYPERCLIENT_COMMITTED',
		'HYPERCLIENT_ABORTED',
		'HYPERCLIENT_UNKNOWNSPACE',
		'HYPERCLIENT_COORDFAIL',
		'HYPERCLIENT_SERVERERROR',
		'HYPERCLIENT_POLLFAILED',
		'HYPERCLIENT_OVERFLOW',
		'HYPERCLIENT_RECONFIGURE',
		'HYPERCLIENT_TIMEOUT',
		'HYPERCLIENT_UNKNOWNATTR',
		'HYPERCLIENT_DUPEATTR',
		'HYPERCLIENT_NONEPENDING',
		'HYPERCLIENT_DONTUSEKEY',
		'HYPERCLIENT_WRONGTYPE',
		'HYPERCLIENT_NOMEM',
		'HYPERCLIENT_BADCONFIG',
		'HYPERCLIENT_BADSPACE',
		'HYPERCLIENT_DUPLICATE',
		'HYPERCLIENT_INTERRUPTED',
		'HYPERCLIENT_CLUSTER_JUMP',
		'HYPERCLIENT_COORD_LOGGED',
		'HYPERCLIENT_INTERNAL',
		'HYPERCLIENT_EXCEPTION',
		'HYPERCLIENT_GARBAGE'
	]	
);

my %seen;
foreach my $package ( keys %EXPORT_TAGS ) {
	my $super_package = $package;
	$super_package =~ s/\/.*$//;
	push( @{ $EXPORT_TAGS{$super_package} }, @{ $EXPORT_TAGS{$package} } )
		if $super_package ne $package;
	push( @EXPORT_OK, grep { !$seen{$_}++ } @{ $EXPORT_TAGS{$package} } );
}
use Data::Dumper;



use constant {
 HYPERCLIENT_SUCCESS      => 8448,
 HYPERCLIENT_NOTFOUND     => 8449,
 HYPERCLIENT_SEARCHDONE   => 8450,
 HYPERCLIENT_CMPFAIL      => 8451,
 HYPERCLIENT_READONLY     => 8452,
 HYPERCLIENT_COMMITTED    => 8510,
 HYPERCLIENT_ABORTED      => 8511,
# Error conditions 
 HYPERCLIENT_UNKNOWNSPACE => 8512,
 HYPERCLIENT_COORDFAIL    => 8513,
 HYPERCLIENT_SERVERERROR  => 8514,
 HYPERCLIENT_POLLFAILED   => 8515,
 HYPERCLIENT_OVERFLOW     => 8516,
 HYPERCLIENT_RECONFIGURE  => 8517,
 HYPERCLIENT_TIMEOUT      => 8519,
 HYPERCLIENT_UNKNOWNATTR  => 8520,
 HYPERCLIENT_DUPEATTR     => 8521,
 HYPERCLIENT_NONEPENDING  => 8523,
 HYPERCLIENT_DONTUSEKEY   => 8524,
 HYPERCLIENT_WRONGTYPE    => 8525,
 HYPERCLIENT_NOMEM        => 8526,
 HYPERCLIENT_BADCONFIG    => 8527,
 HYPERCLIENT_BADSPACE     => 8528,
 HYPERCLIENT_DUPLICATE    => 8529,
 HYPERCLIENT_INTERRUPTED  => 8530,
 HYPERCLIENT_CLUSTER_JUMP => 8531,
 HYPERCLIENT_COORD_LOGGED => 8532,
#  This should never happen.  It indicates a bug 
 HYPERCLIENT_INTERNAL     => 8573,
 HYPERCLIENT_EXCEPTION    => 8574,
 HYPERCLIENT_GARBAGE      => 8575
};


1;
